name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to EC2 instance
        run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@34.210.46.2

      - name: Pull Docker image
        run: docker pull pratyusshrivastav/dockerfastapi-application:latest

      - name: Run Docker container
        run: docker run -d -p 80:3000 pratyusshrivastav/dockerfastapi-application:latest
