name: Docker Image Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t pratyusshrivastav/dockerfastapi-application:v2 .
        
      - name: Push Docker Image to Docker Hub
        run: docker push pratyusshrivastav/dockerfastapi-application:v2   

      - name: SSH into EC2 Instance and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull pratyusshrivastav/dockerfastapi-application:v2
            #docker stop your-container-name || true
            #docker rm your-container-name || true
            docker run -d --name your-container-name -p 8000:8000 pratyusshrivastav/dockerfastapi-application:v2
