name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull Docker image
        run: docker pull pratyusshrivastav/dockerfastapi-application:latest

      - name: SSH into EC2 and run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop mycontainer-1 || true
            docker rm mycontainer-1 || true
            docker run -d --name mycontainer-1 -p 8000:8000 pratyusshrivastav/dockerfastapi-application:latest
