name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t pratyusshrivastav/dockerfastapi-application:v1 .
        
      - name: Push Docker Image to Docker Hub
        run: docker push pratyusshrivastav/dockerfastapi-application:v1   

  
